""" List of contractions with single quote, apostrophe and no quote"""

CONTRACTIONS = {
    "ain't": 'am not',
    'aint': 'am not',
    'ain’t': 'am not',
    "aren't": 'are not',
    'arent': 'are not',
    'aren’t': 'are not',
    "can't": 'cannot',
    'cant': 'cannot',
    'can’t': 'cannot',
    "can't've": 'cannot have',
    'cantve': 'cannot have',
    'can’t’ve': 'cannot have',
    "'cause": 'because',
    'cause': 'because',
    '’cause': 'because',
    "could've": 'could have',
    'couldve': 'could have',
    'could’ve': 'could have',
    "couldn't": 'could not',
    'couldnt': 'could not',
    'couldn’t': 'could not',
    "couldn't've": 'could not have',
    'couldntve': 'could not have',
    'couldn’t’ve': 'could not have',
    "didn't": 'did not',
    'didnt': 'did not',
    'didn’t': 'did not',
    "doesn't": 'does not',
    'doesnt': 'does not',
    'doesn’t': 'does not',
    "don't": 'do not',
    'dont': 'do not',
    'don’t': 'do not',
    "hadn't": 'had not',
    'hadnt': 'had not',
    'hadn’t': 'had not',
    "hadn't've": 'had not have',
    'hadntve': 'had not have',
    'hadn’t’ve': 'had not have',
    "hasn't": 'has not',
    'hasnt': 'has not',
    'hasn’t': 'has not',
    "haven't": 'have not',
    'havent': 'have not',
    'haven’t': 'have not',
    "he'd": 'he had',
    'hed': 'he had',
    'he’d': 'he had',
    "he'd've": 'he would have',
    'hedve': 'he would have',
    'he’d’ve': 'he would have',
    "he'll": 'he will',
    'hell': 'he will',
    'he’ll': 'he will',
    "he'll've": 'he will have',
    'hellve': 'he will have',
    'he’ll’ve': 'he will have',
    "he's": 'he is',
    'hes': 'he is',
    'he’s': 'he is',
    "how'd": 'how did',
    'howd': 'how did',
    'how’d': 'how did',
    "how'd'y": 'how do you',
    'howdy': 'how do you',
    'how’d’y': 'how do you',
    "how'll": 'how will',
    'howll': 'how will',
    'how’ll': 'how will',
    "how's": 'how is',
    'hows': 'how is',
    'how’s': 'how is',
    "i'd": 'i had',
    'id': 'i had',
    'i’d': 'i had',
    "i'd've": 'i would have',
    'idve': 'i would have',
    'i’d’ve': 'i would have',
    "i'll": 'i will',
    'ill': 'i will',
    'i’ll': 'i will',
    "i'll've": 'i will have',
    'illve': 'i will have',
    'i’ll’ve': 'i will have',
    "i'm": 'i am',
    'im': 'i am',
    'i’m': 'i am',
    "i've": 'i have',
    'ive': 'i have',
    'i’ve': 'i have',
    "isn't": 'is not',
    'isnt': 'is not',
    'isn’t': 'is not',
    "it'd": 'it had',
    'itd': 'it had',
    'it’d': 'it had',
    "it'd've": 'it would have',
    'itdve': 'it would have',
    'it’d’ve': 'it would have',
    "it'll": 'it will',
    'itll': 'it will',
    'it’ll': 'it will',
    "it'll've": 'iit will have',
    'itllve': 'iit will have',
    'it’ll’ve': 'iit will have',
    "it's": 'it is',
    'its': 'it is',
    'it’s': 'it is',
    "let's": 'let us',
    'lets': 'let us',
    'let’s': 'let us',
    "ma'am": 'madam',
    'maam': 'madam',
    'ma’am': 'madam',
    "mayn't": 'may not',
    'maynt': 'may not',
    'mayn’t': 'may not',
    "might've": 'might have',
    'mightve': 'might have',
    'might’ve': 'might have',
    "mightn't": 'might not',
    'mightnt': 'might not',
    'mightn’t': 'might not',
    "mightn't've": 'might not have',
    'mightntve': 'might not have',
    'mightn’t’ve': 'might not have',
    "must've": 'must have',
    'mustve': 'must have',
    'must’ve': 'must have',
    "mustn't": 'must not',
    'mustnt': 'must not',
    'mustn’t': 'must not',
    "mustn't've": 'must not have',
    'mustntve': 'must not have',
    'mustn’t’ve': 'must not have',
    "needn't": 'need not',
    'neednt': 'need not',
    'needn’t': 'need not',
    "needn't've": 'need not have',
    'needntve': 'need not have',
    'needn’t’ve': 'need not have',
    "o'clock": 'of the clock',
    'oclock': 'of the clock',
    'o’clock': 'of the clock',
    "oughtn't": 'ought not',
    'oughtnt': 'ought not',
    'oughtn’t': 'ought not',
    "oughtn't've": 'ought not have',
    'oughtntve': 'ought not have',
    'oughtn’t’ve': 'ought not have',
    "shan't": 'shall not',
    'shant': 'shall not',
    'shan’t': 'shall not',
    "sha'n't": 'shall not',
    'sha’n’t': 'shall not',
    "shan't've": 'shall not have',
    'shantve': 'shall not have',
    'shan’t’ve': 'shall not have',
    "she'd": 'she had',
    'shed': 'she had',
    'she’d': 'she had',
    "she'd've": 'she would have',
    'shedve': 'she would have',
    'she’d’ve': 'she would have',
    "she'll": 'she will',
    'shell': 'she will',
    'she’ll': 'she will',
    "she'll've": 'she will have',
    'shellve': 'she will have',
    'she’ll’ve': 'she will have',
    "she's": 'she is',
    'shes': 'she is',
    'she’s': 'she is',
    "should've": 'should have',
    'shouldve': 'should have',
    'should’ve': 'should have',
    "shouldn't": 'should not',
    'shouldnt': 'should not',
    'shouldn’t': 'should not',
    "shouldn't've": 'should not have',
    'shouldntve': 'should not have',
    'shouldn’t’ve': 'should not have',
    "so've": 'so have',
    'sove': 'so have',
    'so’ve': 'so have',
    "so's": 'so is',
    'sos': 'so is',
    'so’s': 'so is',
    "that'd": 'that had',
    'thatd': 'that had',
    'that’d': 'that had',
    "that'd've": 'that would have',
    'thatdve': 'that would have',
    'that’d’ve': 'that would have',
    "that's": 'that is',
    'thats': 'that is',
    'that’s': 'that is',
    "there'd": 'there had',
    'thered': 'there had',
    'there’d': 'there had',
    "there'd've": 'there would have',
    'theredve': 'there would have',
    'there’d’ve': 'there would have',
    "there's": 'there is',
    'theres': 'there is',
    'there’s': 'there is',
    "they'd": 'they had',
    'theyd': 'they had',
    'they’d': 'they had',
    "they'd've": 'they would have',
    'theydve': 'they would have',
    'they’d’ve': 'they would have',
    "they'll": 'they will',
    'theyll': 'they will',
    'they’ll': 'they will',
    "they'll've": 'they will have',
    'theyllve': 'they will have',
    'they’ll’ve': 'they will have',
    "they're": 'they are',
    'theyre': 'they are',
    'they’re': 'they are',
    "they've": 'they have',
    'theyve': 'they have',
    'they’ve': 'they have',
    "to've": 'to have',
    'tove': 'to have',
    'to’ve': 'to have',
    "wasn't": 'was not',
    'wasnt': 'was not',
    'wasn’t': 'was not',
    "we'd": 'we had',
    'wed': 'we had',
    'we’d': 'we had',
    "we'd've": 'we would have',
    'wedve': 'we would have',
    'we’d’ve': 'we would have',
    "we'll": 'we will',
    'well': 'we will',
    'we’ll': 'we will',
    "we'll've": 'we will have',
    'wellve': 'we will have',
    'we’ll’ve': 'we will have',
    "we're": 'we are',
    'were': 'we are',
    'we’re': 'we are',
    "we've": 'we have',
    'weve': 'we have',
    'we’ve': 'we have',
    "weren't": 'were not',
    'werent': 'were not',
    'weren’t': 'were not',
    "what'll": 'what will',
    'whatll': 'what will',
    'what’ll': 'what will',
    "what'll've": 'what will have',
    'whatllve': 'what will have',
    'what’ll’ve': 'what will have',
    "what're": 'what are',
    'whatre': 'what are',
    'what’re': 'what are',
    "what's": 'what is',
    'whats': 'what is',
    'what’s': 'what is',
    "what've": 'what have',
    'whatve': 'what have',
    'what’ve': 'what have',
    "when's": 'when is',
    'whens': 'when is',
    'when’s': 'when is',
    "when've": 'when have',
    'whenve': 'when have',
    'when’ve': 'when have',
    "where'd": 'where did',
    'whered': 'where did',
    'where’d': 'where did',
    "where's": 'where is',
    'wheres': 'where is',
    'where’s': 'where is',
    "where've": 'where have',
    'whereve': 'where have',
    'where’ve': 'where have',
    "who'll": 'who will',
    'wholl': 'who will',
    'who’ll': 'who will',
    "who'll've": 'who will have',
    'whollve': 'who will have',
    'who’ll’ve': 'who will have',
    "who's": 'who is',
    'whos': 'who is',
    'who’s': 'who is',
    "who've": 'who have',
    'whove': 'who have',
    'who’ve': 'who have',
    "why's": 'why is',
    'whys': 'why is',
    'why’s': 'why is',
    "why've": 'why have',
    'whyve': 'why have',
    'why’ve': 'why have',
    "will've": 'will have',
    'willve': 'will have',
    'will’ve': 'will have',
    "won't": 'will not',
    'wont': 'will not',
    'won’t': 'will not',
    "won't've": 'will not have',
    'wontve': 'will not have',
    'won’t’ve': 'will not have',
    "would've": 'would have',
    'wouldve': 'would have',
    'would’ve': 'would have',
    "wouldn't": 'would not',
    'wouldnt': 'would not',
    'wouldn’t': 'would not',
    "wouldn't've": 'would not have',
    'wouldntve': 'would not have',
    'wouldn’t’ve': 'would not have',
    "y'all": 'you all',
    'yall': 'you all',
    'y’all': 'you all',
    "y'all'd": 'you all would',
    'yalld': 'you all would',
    'y’all’d': 'you all would',
    "y'all'd've": 'you all would have',
    'yalldve': 'you all would have',
    'y’all’d’ve': 'you all would have',
    "y'all're": 'you all are',
    'yallre': 'you all are',
    'y’all’re': 'you all are',
    "y'all've": 'you all have',
    'yallve': 'you all have',
    'y’all’ve': 'you all have',
    "you'd": 'you had',
    'youd': 'you had',
    'you’d': 'you had',
    "you'd've": 'you would have',
    'youdve': 'you would have',
    'you’d’ve': 'you would have',
    "you'll": 'you will',
    'youll': 'you will',
    'you’ll': 'you will',
    "you'll've": 'you will have',
    'youllve': 'you will have',
    'you’ll’ve': 'you will have',
    "you're": 'you are',
    'youre': 'you are',
    'you’re': 'you are',
    "you've": 'you have',
    'youve': 'you have',
    'you’ve': 'you have'
 }
